service: my-local-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:

  addresses:
    handler: dist/manager.handler
    events:
      - http: "GET /addresses"
      - http: "GET /addresses/{id}"
      - http: "POST /addresses"
      - http: "PUT /addresses/{id}"
      - http: "DELETE /addresses/{id}"